### ISSUE TITLE
Notification compatibility and unnecessary menu removal

### ISSUE THREAD

**Issue by root-kernelhacker** [cuynu/VancedxMicroG#9]
I found this while looking for a microg that receives notifications from YouTube Revance Extended (inotia00).  

I received the v0.2.28.232516 version from the website and tested it, but there was no problem, so I searched and found that the build was distributed here.  

I downloaded and installed the latest version, v0.2.28.233013, from here, and I'll have to test it for about a day to see if the notifications work, but I'm writing because there are weird menus in both the old and new versions.  

If you look at the microg menu, there is a view source code menu that shows the github source code below and a menu called test1 in the right area, but it doesn't work.  

It seems like an unnecessary menu. 
Can I delete it?  

Also, since all the architectures are included, can you build them separately for each architecture?  
(I need is a build for v8a) Thanks!  

Finally, is there any problem with compatibility with Reasoned Extended?

**Comment by hirenshah** [comment]
I noticed that test option too 😂

**Comment by cuynu** [comment]
fixed test option
